CC = gcc
CXX = g++
LDLIBS +=  -lm -lpthread
CFLAGS += -std=c99 -I/usr/local/include
CXXFLAGS += -lpthread
GCD_CC = clang
GCD_LDLIBS += -lBlocksRuntime -ldispatch -lpthread_workqueue -lpthread
GCD_CFLAGS += -fblocks
